apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    type: myType
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-pod
  template:
    metadata:
      labels:
        name: frontend-pod
    spec:
      containers:
      - name: frontend-pod
        image: erik/frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 4200
          protocol: TCP
          
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  type: NodePort
  ports:
  - nodePort: 30090
    port: 4200
    targetPort: 4200
  selector:
    name: frontend-pod
